  development:
    adapter: postgresql
    encoding: unicode
    database: diabetic_diary_backend_development
    pool: 5
    username: postgres
    password:

  test:
    adapter: postgresql
    encoding: unicode
    database: diabetic_diary_backend_test
    pool: 5
    username: postgres
    password:

  production:
    adapter: postgresql
    encoding: unicode
    database: diabetic_diary_backend_production
    pool: 5
    username: postgres
    password: